midgard: fix build error with latest android-4.9 kernel
The latest android-4.9 kernel is based on stable kernel 4.9.104, and
mali700 midgard driver fails to build with it.

  CC      drivers/hisilicon/msp/gpu/mali700/drivers/gpu/arm/midgard/mali_kbase_sync_file.o
drivers/hisilicon/msp/gpu/mali700/drivers/gpu/arm/midgard/mali_kbase_sync_file.c: In function 'kbase_sync_fence_info_get':
drivers/hisilicon/msp/gpu/mali700/drivers/gpu/arm/midgard/mali_kbase_sync_file.c:283:21: error: 'struct fence' has no member named 'status'
   int status = fence->status;
                     ^
make[7]: *** [drivers/hisilicon/msp/gpu/mali700/drivers/gpu/arm/midgard/mali_kbase_sync_file.o] Error 1

This is becasue that commit f5e0724e76c2 ("dma-fence: Introduce
drm_fence_set_error() helper") gets back ported into stable kernel since
version 4.9.68.  Update the kernel version check to fix the errors.

Signed-off-by: Shawn Guo <shawn.guo@linaro.org>